### ISSUE TITLE
Design glFusion Social CMS Plugin

### ISSUE THREAD

**Issue by buddilla** [glFusion/glfusion#112]
Create social media CMS plugin which implements features already in the wild into glFusions functions such as those from facebook, pligg cms, buddy press, elgg cms ect.

Update: I think this one is very useful and important to help create user generated content. This in most cases helps make sites grow quickly in popularity. That's a good thing for glFusion because that will expand it's install base which in turn will get more contributors, which makes Mark happy and we always like when Mark is happy. 

I will be adding in the comments features that I think would most benefit glfusion as I think of them, others should too. Most of the functions for a social environment already exist in glfusion and just need some (hopefully) small tweaks. Some of these include subscriptions, users, groups, posting stories, story ratings, user media gallery, extendable user profile, privacy settings ect. The admin pages might be the difficult part.

**Comment by buddilla** [comment]
The biggest part of any social media site is the feed. Users should have their own home page with any of their subscribed feeds. glFusion already supports subscriptions and now has the ability to have infinite scrolling. Just have to figure out how to turn that into a "Users" home page.

**Comment by walterrowe** [comment]
How about the ability for content in glFusion to be syndicated to other platforms like Facebook, etc. for sites that also have social media pages, content from the site could also be pushed to those social media pages.

**Comment by mark0263** [comment]
with social share - i think most of this functionality is already in place.
