### ISSUE TITLE
Add Commenting to .thtml Files

### ISSUE THREAD

**Issue by buddilla** [glFusion/glfusion#122]
Add comments in each template file that shows what glfusion tags are available in specific templates.

**Comment by mark0263** [comment]
I would rather see the documentation in the wiki instead of embedded in the templates - I like the idea of documenting the available tags, etc., but I'm not sure putting them in the actual template is the right place to document it...

**Comment by buddilla** [comment]
Your probably right, I just thought I would make it easier for making themes if the files showed what was available in the templates such as in storytext.thtml file story_image, story_subtitle, story_url ect...

**Comment by walterrowe** [comment]
I agree with Mark. Documentation should be maintained in a single place. Plus, some templates are used in numerous places. Keeping all the documentation in the wiki makes sense. There are global template variables and there are plugin specific template variables.
