### ISSUE TITLE
Allow php within Autotags

### ISSUE THREAD

**Issue by buddilla** [glFusion/glfusion#124]
this would allow things like [headlines:{story_topic_name} ]

Maybe adding double brackets could tell the process to execute the code inside the autotag first. That way when it's parsed it won't have to read the whole autotag first to execute code. 

Or maybe another way could be like a hook [config_autotag:headlines={story_topic_name}, display={!if story_alternate_topic_name}5{else}10{end if} >> [headlines:  ]] . config_autotag would be the only autotag that allows code within it.

**Comment by mark0263** [comment]
The security implications of this are huge!  The current auto tag system allows for user developed auto tags by implementing the proper class - there are several good examples to work from.  This is the preferred method to 'write code' or use PHP with an auto tag.
