### ISSUE TITLE
Web Based Email Client

### ISSUE THREAD

**Issue by buddilla** [glFusion/glfusion#125]
Create a glfusion wrapper for a web based email client such as roundcube can be ran within glfusion. Unless a native one can be made which would be even better.

**Comment by walterrowe** [comment]
I don't agree with you. Email should be outside of glFusion. We have a private message plugin for users to send messages. There are far too many email systems out there. You can't pick just one and you can't support them all.

**Comment by mark0263** [comment]
I think the challenges to build and maintain an integration to an external mail system would be more effort than the benefit it would provide.
