### ISSUE TITLE
Increase the number of characters for Topic id

### ISSUE THREAD

**Issue by AlexL777** [glFusion/glfusion#13]
Dear Webdevelopers,

I use side yesterday the latest version of glFusion and am interested in how you can increase the number of characters for the topic id. I would like to always add a unique ID there and the number of characters is much too low.

How can you do it?

By the way, I'm sorry that I have to create an issue here and can not post in the support forum. For me it is much easier, because I'm first, often at GitHub and secondly, I have here an account.

**Comment by mark0263** [comment]
Unfortunately - it is not as simple as changing one database element - the topic_id is used in several places.  I agree it should be larger - I will make the modification in the 1.5.0 codebase

**Comment by AlexL777** [comment]
Ok, thank you very much for your answer. Then I'll get on that. No problem.

**Comment by mark0263** [comment]
Topic ID and description have been increased to 128 bytes. 5bd8a3c93941b0890fea7dc34503edc1a05bf95a
