### ISSUE TITLE
Allow security token ttl to be configured

### ISSUE THREAD

**Issue by mark0263** [glFusion/glfusion#131]
The security token ttl is hard coded to 1200 seconds.  Let's make this configurable.,

**Comment by buddilla** [comment]
I second this!!!

**Comment by mark0263** [comment]
This is now an advanced configuration setting that can be changed in the $_SYSTEM vars in siteconfig.php

**Comment by mark0263** [comment]
Fixed with  commit 32cb17c639d6a37f40657114ee3a48af643e04dd
