### ISSUE TITLE
Auto Enable/Disable block on given date/time

### ISSUE THREAD

**Issue by spacequad** [glFusion/glfusion#135]
I think a nice feature to have for the blocks would be to have an auto enable/disable block feature.  Similar to the stories.  Lets say you wanted to advertise a certain block during a given time/date and wanted to set that block up ahead of time, then all you would have to do is set the dates and be done with it.   You could even extend this to groups to only show to certain group privs.

Michael

**Comment by walterrowe** [comment]
Banner plugin does this but may be more than you're looking for.

Has anyone tested banner with glfusiion 1.6 and uikit?

Walter

**Comment by buddilla** [comment]
I think this is a great idea. It would also be nice to make this global for static pages and stories then extend it so it can loop. That way companies can have things like Discounts(blocks, Pages, Stories) that automatically post and un-post themselves every year, month, week ect. Including this for themes would be a nice feature. Such as changing a theme for Halloween, Thanksgiving, Christmas ect. automatically then back would be a great feature too. Using the uikit date picker would be a great way to help on the front end. http://getuikit.com/docs/datepicker.html

**Comment by spacequad** [comment]
Walter,
The banner plugin does install and work for the most part, but does have some inherent issues/bugs that still need to be fixed.  I just tested it and the bugs are still in the current github version.
