### ISSUE TITLE
Remove links from glFusion NoFolow from forum

### ISSUE THREAD

**Issue by AlexL777** [glFusion/glfusion#14]
Hello Webdevelopers,

how to make dofollow forum at glFusion from nofollow? I know my links that I put in the forum and I want that the search engines can follow the links. Spam does not come here now times.

How can you do it? Thank you in advance.

**Comment by mark0263** [comment]
There is no configuration option for this - you would have to change the source code directly - the nofollow is added in private/plugins/forum/include/format.inc.php - around line 73 - you will see this function:

  function do_bbcode_url ($action, $attributes, $content, $params, $node_object) {
    global $_FF_CONF;

    if ($action == 'validate') {
        return true;
    }

    if (!isset ($attributes['default'])) {
        if ( stristr($content,'http') ) {
            return '<a href="'.strip_tags($content).'" rel="nofollow">'.@htmlspecialchars ($content,ENT_QUOTES, COM_getEncodingt()).'</a>';
        } else {
            return '<a href="http://'.strip_tags($content).'" rel="nofollow">'.@htmlspecialchars ($content,ENT_QUOTES, COM_getEncodingt()).'</a>';

        }
    }
    if ( stristr($attributes['default'],'http') ) {
        return '<a href="'.strip_tags($attributes['default']).'" rel="nofollow">'.$content.'</a>';
    } else {
        return '<a href="http://'.strip_tags($attributes['default']).'" rel="nofollow">'.$content.'</a>';
    }
  }

Remove the rel="nofollow" and that should do it.

**Comment by AlexL777** [comment]
Thank you, that helped me a lot.
