### ISSUE TITLE
Allow Oauth Users to Have Custom Display Name

### ISSUE THREAD

**Issue by buddilla** [glFusion/glfusion#143]
When a user logs in via oauth the user is supplied with a permanent system user name. In my case on the glfusion home page my user name is Andrew8925(Facebook oauth). Would it be posable to allow for a user to change their user name. I'm guessing that this could be done by using the system supplied name as a userid(so the system can avoid collisions) and use the custom username as an alias instead. Obviously the system will need to check for user alias to avoid user alias collision.

The basic idea is:

if userid has alias
display alias
else
display userid

**Comment by mark0263** [comment]
There is an option in glFusion to allow users to change their username - this can be used to create a better username if the user wishes.
