### ISSUE TITLE
SEO-friendly URLs in the Forum of glFusion  - last Version

### ISSUE THREAD

**Issue by AlexL777** [glFusion/glfusion#15]
Hello Webdevelopers, I must turn to you myself again.

I'm still a novice with the GlFusion CMS and would like to know how to do SEO-friendly URLs in glFusion Forum.

How must look like the .htaccess content? It is quite hard to find on the internet and in the English support forum I then already looked around and found nothing.

How should the .htaccess look like? About useful advice, I am pleased and thank you.

**Comment by dtrumbower** [comment]
Go into the Site configuration screen and Enable URL Rewrite.

https://www.glfusion.org/wiki/glfusion:configuration?s[]=url&s[]=friendly#site1
