### ISSUE TITLE
How can you display static pages in a block

### ISSUE THREAD

**Issue by AlexL777** [glFusion/glfusion#16]
Hello Developers,

I have a question namely how can you display in a block all static pages in Glfusion? For me it does not work with it and I have created two static pages and I choose the blocks left and right to create, but it is not displayed in the frontend.

Can you maybe create a new block and display the static pages so? However, do I have to know "block_xxxxx" parameter.

Can you help me somehow? Thank you in advance.

**Comment by dtrumbower** [comment]
https://www.glfusion.org/wiki/glfusion:staticpages?s[]=staticpages

**Comment by mark0263** [comment]
I think you are asking how to have the left or right blocks displayed when viewing a static page.

Blocks are dependent on the theme - if you are using the CMS theme, there are no left blocks - the blocks are re-arranged so the left blocks actually appear on the right and the right blocks are moved to the footer.  

For Nouveau based themes - the blocks should appear on the left or right depending on how you setup the page.

Can you tell me more info on specifically what settings you have on the static page?

**Comment by AlexL777** [comment]
Well I managed and I have used the option that right blocks are always displayed. Then I created a new block and involved in the visual editor my links to static pages. So I wanted to have it as well.

On a static page right blocks are displayed with me. I can live with that :)
