### ISSUE TITLE
Comment autotag

### ISSUE THREAD

**Issue by buddilla** [glFusion/glfusion#163]
Usage
[comment:id]

id is the id of the story/mediagallery/download ect...

if an id is added that does not exist the autotag creates a stand alone comment section with that id. 

This will allow for various hacks especially with third party comment engines(no ajax over head).

When used as a stand alone comment it could be used for reviews of company pages.

Could help with putting comments in static pages and blocks.

Or maybe make a headlines autotag equivalent for comments.
[comment:all media:story display:10]
Would display the comments from 10 of the latest stories from all topics (just like headlines)which could be placed in a block as a slideshow labeled latest comments.

Just a thought...

**Comment by mark0263** [comment]
Static pages already support comments directly.  Let's expand on the use case for this - building a comment auto tag is pretty complex as it needs to handle displaying comments and submission of comments - all while supporting the appropriate security controls.

From a display perspective - one of the challenges with 3rd party comments is pulling the last XX comments for a site - we're currently doing this with an RSS feed at glfusion.org - there are some APIs for Disqus, but I don't know if there are APIs for FB Comments.  So this is not as easy as just selecting comments from a table like we would do for internal comments. 

Help me better understand how this would be used so we can determine if it is worth the large investment of development.

**Comment by walterrowe** [comment]
I would prefer to see an investment new in several different layouts oriented towards different kinds of web sites. Think about news sites, rich media sites, blogs, corporate sites, one-column or multi-column content, etc. Even with UIKIT, it still isn’t easy to “redesign” the CMS layout to suit different audiences and purposes.

**Comment by mark0263** [comment]
Please keep comments specific to this issue / feature request - if we can't stay on topic - I'll lock the conversation.

**Comment by buddilla** [comment]
This was more of idea type request...

But for instance when using disqus placed in a right block it would allow for moving the comments to the right. On the index page people would be able to call a specific story or stories of comments and have them in a block called something like Latest Hot Comments, in reality it would just be the last posted story comment section.

This would allow for custom comments on specific parts of pages. Such as a custom index page with a section called Trending Comments.

I'm just thinking this would add another layer of customizability for comment into glFusion.

Shoot with a little trickery I could turn disqus into a chatroom on anypage anywhere on the page. 

Disqus should be pretty easy I think just plug in the specific attributes...
 <a name="comment_entry"></a>
            <div id="disqus_thread"></div>
            <script>
                var disqus_config = function () {
                    this.page.url = 'http://www.example.com/example_page_id';
                    this.page.identifier = 'example_page_id';
                    this.page.title = 'Example Page';
                };
                (function() {
                    var d = document, s = d.createElement('script');
                    s.src = '//thedailygoblin.disqus.com/embed.js';
                    s.setAttribute('data-timestamp', +new Date());
                    (d.head || d.body).appendChild(s);
                })();
            </script>
            <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

Slightly of topic, With a little rework disqus could be used replace the forums as well.

**Comment by buddilla** [comment]
Remember this is just a suggestion... I just thought it was an interesting idea... I know I would use the autotag. It might be unique only because I haven't seen anybody do this before.
