### ISSUE TITLE
feature request: allow autotags in About Profile field

### ISSUE THREAD

**Issue by walterrowe** [glFusion/glfusion#165]
Allow use of autotags in profile About field. Articles display this field and I would like authors to be able to have their website links included there in a safe and secure manner that protects the site. An autotag for the website link in their profile could be added to the About text.

**Comment by mark0263** [comment]
Implemented with commit 6595e5173080ef910e710afe1399ce6a713eab6c

**Comment by walterrowe** [comment]
I downloaded this dev update to allow autotag in the about_user field. It does insert a link to a home page. Unfortunately, the [user:homepage] links to the home page of the currently logged in user vs the article author.

I wonder if the user autotag might gain some flexibility by allowing an option :id parameter as in [user:id p1] vs the current [user:p1] implementation. This would allow one to specify which user and then expand the p1 profile field for that specific user. If the :id is left off then it can default to the logged in user as it does today?

So you expand p1 for user :id with [user:id p1] or expand p1 for the logged in user with [user p1]?
