### ISSUE TITLE
Blank Page on Plugin Update/Install Error

### ISSUE THREAD

**Issue by buddilla** [glFusion/glfusion#169]
When install or update goes bad a blank(misnomer still has header and footer) page shows with error and no escape back too plugin admin.

Page should return to plugin admin and display error based on siteconfig.php option this would be consistent with overall UI elements.

**Comment by mark0263** [comment]
The problem was that the upload routines were separated from the other plugin admin routines (separate source files).  I've merged them together and now handle errors properly :) 00dd9534badc44461a5b81e5fb0e236f7e607827
