### ISSUE TITLE
error with utf8mb4 upgrade

### ISSUE THREAD

**Issue by walterrowe** [glFusion/glfusion#185]
Table: gl_logo Column: config_name :: 1071: Specified key was too long; max key length is 767 bytes
![utf8mb4-upgrade-error](https://cloud.githubusercontent.com/assets/7131288/20462811/52f3db7a-aef4-11e6-89b0-906ea1d5291a.png)

**Comment by mark0263** [comment]
Odd - that table / field was adjusted to 128 bytes in the v1.5.1 to v1.6.0 upgrade. I'll force it again in the 1.6.3 upgrade - no harm doing it twice.

**Comment by walterrowe** [comment]
I think I skipped the 1.6.0 upgrade and went straight to 1.6.1 on all my sites. Would that be the reason I missed it?
