### ISSUE TITLE
dbbackup.js - DB table backup progress bullets

### ISSUE THREAD

**Issue by walterrowe** [glFusion/glfusion#186]
When a table backs up, the progress bullets initially have a space after the table name. If it takes long enough, the bullets clear and start over, but without a space after the table name. Add a "&nbsp;" to the "&bull;" when table backup progress restarts. I found the place in dbbackup.min.js, but don't have access to the dbadmin.js source to fix it myself. I submitted a fix previously before this was moved to aJax JS.

**Comment by mark0263** [comment]
Fixed with 524c6c45ae452917509bc0bf4fbd655db9985724
