### ISSUE TITLE
No Translation for "Global Settings"

### ISSUE THREAD

**Issue by matrox66** [glFusion/glfusion#196]
admin/story.php

line 658

`    $menu_arr = array (
        array('url' => $_CONF['site_admin_url'] . '/story.php',
              'text' => $LANG_ADMIN['story_list']),
        array('url' => $_CONF['site_admin_url'] . '/moderation.php',
              'text' => $LANG_ADMIN['submissions']));
        if ( SEC_inGroup('Root')) {
            $menu_arr[] = array('url' => $_CONF['site_admin_url'] . '/story.php?global=x',
                      'text' => 'Global Settings');
        }`

and line 475

`    $menu_arr = array (
        array('url' => $_CONF['site_admin_url'] . '/story.php?edit=x',
              'text' => $LANG_ADMIN['create_new']),
        array('url' => $_CONF['site_admin_url'] . '/moderation.php',
              'text' => $LANG_ADMIN['submissions']));
        if ( SEC_inGroup('Root')) {
            $menu_arr[] = array('url' => $_CONF['site_admin_url'] . '/story.php?global=x',
                      'text' => 'Global Settings');
        }`

**Comment by mark0263** [comment]
Resolved with commit cb73da7db7bf19097e15d89e5703e2e572c49c2a
