### ISSUE TITLE
No Translation for "Ban IPs"

### ISSUE THREAD

**Issue by matrox66** [glFusion/glfusion#197]
admin/plugins/bad_behavior2/index.php

line 104

`    $menu_arr = array (
        array('url' => $_CONF['site_admin_url'].'/plugins/bad_behavior2/ban.php',
              'text' => 'List Banned IPs'),
        array('url' => $_CONF['site_admin_url'].'/plugins/bad_behavior2/ban.php?mode=add',
              'text' => 'Ban IPs'),
        array('url' => $_CONF['site_admin_url'],
              'text' => $LANG_ADMIN['admin_home'])
    );`

admin/plugins/bad_behavior2/ban.php

line 225

`    $retval .= COM_startBlock ($LANG_BAD_BEHAVIOR['plugin_display_name'] . ' - ' . 'Ban IPs', '',`

**Comment by mark0263** [comment]
Resolved with commit ed4422126f82e5bf70007ca84c3ea6c342113fa7
