### ISSUE TITLE
AD Support / New User Registration 

### ISSUE THREAD

**Issue by mark0263** [glFusion/glfusion#2]
I have a internal work related website I manage. I have configured it for AD authentication. I learned today that you must enable new user registration in order for first-time AD logins to be successful.

What I would like is to allow AD authentication of new users and have them registered, but to not provide a registration link on the page. I can modify the templates to accomplish this. I would like the configuration settings for a future glFusion release to provide this.

**Comment by mark0263** [comment]
Comments from the forum:

3rd Party LDAP appears. LDAP users already known to the site can authenticate and log in successfully. Only new users are denied.

I did find one problem that may have been the root cause for this specific user. My config said the minimum user ID had to be 4 characters or longer, and this LDAP account had 3 characters so the site was passing an empty string to the LDAP authentication. I think an unknown user who provides an account name shorter than the permitted length should get a message presented back to them (or an error written in the error log) indicating so.

Now that I discovered this problem with length of user ID, I need to delete a known LDAP user and have them try to log in again with registration disabled so that I can test whether the length of the user ID was the actual issue all along. I looked in the code and also could not see any reason why disabling registration would prevent an new LDAP user from logging in and getting automatically registered.

**Comment by walterrowe** [comment]
For most users you see an ldap query string of the form:

CN=username,OU=path,OU=to,OU=users,DN=some,DN=domain,DN=name

When the username string entered is shorter than the minimum allowed in the users config admin page, an ldap query is still performed but with an empty CN string like this:

CN=,OU=path,OU=to,OU=users,DN=some,DN=domain,DN=name

**Comment by mark0263** [comment]
If the username was too short, it was set to '' - added check to 3rd party login to ensure username is not blank.  6e1d82b91a42d20e2605b58b49babd0a9bfcb916
