### ISSUE TITLE
Plugins can not be updated

### ISSUE THREAD

**Issue by AlexL777** [glFusion/glfusion#204]
Dear developers,

Unfortunately the plugins can not be installed or updated in the Glfusion version 1.6.3. I wanted to upload the ZIP plugin package under plugins in the backend, but nothing is displayed. Where can this come from?

How can I update my plugins otherwise?

DokuWiki and the tag plugin I have to update, which unfortunately does not work.

Thanks in advance.

**Comment by leegarner** [comment]
You can check the support forum at
https://www.glfusion.org/forum/viewtopic.php?showtopic=43148. There's a new
plugins.php attachment in one of the later posts that solved the issue for
me.

**Comment by mark0263** [comment]
The plugins.php Lee referenced is included in glFusion v1.6.3.

When you say nothing is displayed - let's dive into this a bit more.

 1. You go to Command & Control
 2. Select File to upload - hit upload
 3. What happens here?  Do you get just a blank screen? 

If you are getting a blank screen - we need to look at why. We may need to enable root debugging (https://www.glfusion.org/wiki/glfusion:configuration:miscellaneous) to get better error messages.

Is there anything in the glFusion error.log file to give a clue?

**Comment by mark0263** [comment]
FYI - we have some documentation on manual installs - https://www.glfusion.org/wiki/glfusion:plugins:dokuwikiplugin:start#manual_installation

**Comment by walterrowe** [comment]
I upgraded several plugins with no issue. Make sure your file / folder permissions and ownership are correct on the server?

Walter

**Comment by AlexL777** [comment]
Hello again,

I have now deleted the tag plugin from the database and could upload it again in the backend as well as install. That works everything then synonymous.

But unfortunately the Tag-Plugin does not work, because it shows me errors in the backend.

I have set the number of keywords to 5, and immediately afterwards the page was refreshed.

Would you please try again the tag plugin? Defines the number of keywords in the plugin options and refresht the page. The number of keywords is 0 to default.

Thanks in advance.

**Comment by mark0263** [comment]
I'm not sure I understand. Let me repeat the issue laying out the steps:

1. You go into Command & Control -> Configuration -> Tag 
2. Set the Max number of keywords to 5
3. You hit Save

After you save, the screen refreshes and the Max number of keywords is back to 0?

Is this correct?

**Comment by AlexL777** [comment]
No, after refresh the web page I got error messages displayed. The number of keywords does not change, ie stays on 5 keywords. So with the plugin settings everything works out.

The only thing is, there are errors that are displayed. I have removed the tag plugin again.

**Comment by mark0263** [comment]
It would be helpful if you could tell us what the error messages are that are displayed.

Also, if you could layout the steps you take to create the problem, similar to what I did above, it will help me duplicate or troubleshoot.

**Comment by mark0263** [comment]
Is there still an issue?  If yes, please provide the error messages that are displayed.
