### ISSUE TITLE
media gallery static sort doesn't static sort

### ISSUE THREAD

**Issue by walterrowe** [glFusion/glfusion#218]
glFusion 1.6.4

I chose "static sort" from a media gallery album admin menu.
I chose "media capture time" and "ascending".
I pressed "save".

The album did not sort by media capture time. I repeated this with other choices, and with both ascending and descending order. None of them worked.

I edited the album preferences and chose "media capture time, ascending" and that DID worked.

**Comment by mark0263** [comment]
I found an issue with the static sorting, but it should have only affected sorting when descending was chosen.  I've fixed that and tested each of the static sort methods in both ascending and descending, all appear to work properly.

**Comment by mark0263** [comment]
You can grab the updated staticsort.thtml template from the develop branch, see commit above, to validate whether this resolved the issue.  I'll close once I get confirmation.

**Comment by mark0263** [comment]
Removed static sort media option from menu if the album already has a sort method selected in album properties. I believe this resolves the issue.

**Comment by walterrowe** [comment]
I agree .. it is confusing to have it if the album preference sort order overrides what you choose from that screen.

If the album has no automatic sorting, would this screen set the sort order album preference?

**Comment by mark0263** [comment]
Using static sort does not change the album properties setting - not sure if updating the properties would be the right thing to do or not - if it did update the properties, it would need to be called out clearly that a permanent album change is also being done. I'm leaning towards keeping it the way it is...Thoughts?

**Comment by walterrowe** [comment]
What is the purpose of having it if it doesn't update the album preferences? It is a per user setting or a global setting for all users? If it is a global setting for all users then why not update the album preferences? That way you can look at the album preferences to see what it is set to.

Walter

**Comment by mark0263** [comment]
A very good question - why have it?  It has been around forever, I honestly don't remember what drove the feature. Seems to me, setting the album properties sort order is what is needed. There is a manual sort capability in Manage Media, where you can set the sequence if the event none of the 'canned' sort methods are appropriate. I think (and will verify) that if you do a manual sorting, it will still be overridden by the album properties setting (unless it is set to no automatic sorting). So I think the right thing to do is this:
 * remove the static sort feature
 * Do not display 'sequence' in manage media if the album properties specifies a sort order (probably disable the field). 

You can still sort by using one of the canned options or manually sequencing the media.

**Comment by walterrowe** [comment]
I'll go way outside the box and suggest (a) yes to what you said, (b) never show sort order on manage media screen – ever, and (c) provide a new menu item to sort manually that gives a UI to manually set the order with thumbnail tiles you can move around. Am I being completely over the top?

Walter

**Comment by walterrowe** [comment]
Can this be closed?
