### ISSUE TITLE
Use Disqus API to log Number of Comments

### ISSUE THREAD

**Issue by buddilla** [glFusion/glfusion#219]
Disqus provides an API to work with, it would be nice to be able to see the number of comments for stories in the site stats. I believe the api will allow this. If this can be done with facebook that would be awesome too.

https://disqus.com/api/docs/

Here are some API Recipies
https://github.com/disqus/DISQUS-API-Recipes

**Comment by mark0263** [comment]
Disqus comment counts are supported via the API / Javascirpt.
