### ISSUE TITLE
Unscaled images cause all links to open in lightbox

### ISSUE THREAD

**Issue by leegarner** [glFusion/glfusion#220]
Found an issue with lib-story.php where "keep_unscaled_images" causes images as well as all other links to open in a lightbox.

Line 1178, after converting all the imageX tags to links, converts all "a href" tags to use lightbox:
            $parsedText = str_replace("a href","a data-uk-lightbox href",$parsedText);

Not sure of the best way around this yet, but lookiing.

**Comment by leegarner** [comment]
One idea, maybe change the setting of lLink_attr for COM_createLink()?
Change line 1170 to:
    $lLink_attr = array(
        'title' => $LANG24[57],
        'data-uk-lightbox' => '',
    );

And remove line 1179

**Comment by mark0263** [comment]
I think your solution will work perfectly!  I'll commit the change shortly...

**Comment by mark0263** [comment]
Committed Lee's fix - also fixed issue where slimbox lightbox did not work properly on story images.
