### ISSUE TITLE
Classifieds Plugin is not properly linked under "Admins only" - new plugin version

### ISSUE THREAD

**Issue by AlexL777** [glFusion/glfusion#226]
Hello Developers,

I've probably discovered a bug in the Classifieds plugin in the new version. It is not properly linked under "Admin only". My glfusion installation is at http://wpzweinull.ch/cms/glfusion and the options of the plugin lead to http://wpzweinull.ch/index.php. There is nothing.

Can you look at this again?

Thanks in advance.

I would like to test this plugin once and I could install it well. But the options are not properly linked.

![glfusion-annoncen-no-correct-linking](https://cloud.githubusercontent.com/assets/7885632/22175037/91802b1c-dfed-11e6-8581-d3dded89f5f7.jpg)

**Comment by mark0263** [comment]
This appears to be an issue with how the Classifieds plugin is returning the menu link. I have opened an issue with the Classifieds GitHub Project Page - https://github.com/leegarner-glfusion/classifieds/issues/3

**Comment by mark0263** [comment]
Moved issue to the Classified GitHub Project Page.

**Comment by leegarner** [comment]
I just uploaded version 1.1.2 to glfusion.org which fixes this issue.

Thanks.
Lee.

**Comment by AlexL777** [comment]
Thank you @leegarner for the quick reaction. Classifieds are now working very well and I have already created my first classifieds.
