### ISSUE TITLE
How to work with tags in glfusion - Glfusion 1.6.4

### ISSUE THREAD

**Issue by AlexL777** [glFusion/glfusion#227]
Hello Developers,

Unfortunately, I can not cope with the tags and tagging in glFusion 1.6.4. There is a TagCloud and the Autotags. How do I create such tags when creating a blog post?

There is a tags page in the frontend of Glfusion and I understand that all tags appear from the portal. In the TagCloud with me at http://wpzweinull.ch/cms/glfusion is also nothing, because I do not understand how I can create such tags.

Thanks in advance.

**Comment by mark0263** [comment]
Have you reviewed the Tag Plugin Documentation at the glFuison CMS Website? https://www.glfusion.org/wiki/glfusion:plugins:tag:start

This should provide a good starting point.

**Comment by AlexL777** [comment]
Thanks, 

tags, I can now embed. I now have this tag configuration as on the screenshot. Unfortunately, tags are truncated in the frontend.

The character length in "bytes" is 128.

Tags in Tamplate Vars I already show what worked well. Here are two screenshots. Such tags as "cms" or "opensource" are truncated.

How can I fix it?


Thanks in advance.
![glfusion-tags-konfiguration](https://cloud.githubusercontent.com/assets/7885632/22175763/f0584c60-dffb-11e6-9615-a193ddb85a1a.jpg)

![glfusion-tags-in-the-frontend](https://cloud.githubusercontent.com/assets/7885632/22175765/fc1eb944-dffb-11e6-9537-d470175edd06.jpg)

**Comment by mark0263** [comment]
Can you show me the Tags in the article editor - see my example screen shot:
![fireshot capture 11 - story editor - glfusion dvlp_ - http___dev glfusion org_admin_story php](https://cloud.githubusercontent.com/assets/1749865/22175800/393cedb2-dfc2-11e6-974d-d1005e94bc4b.png)

**Comment by AlexL777** [comment]
These look like this screenshot.

![tags-in-the-article-editor](https://cloud.githubusercontent.com/assets/7885632/22175870/4523f5e4-dffe-11e6-9f66-8e8cc0641cd1.jpg)

**Comment by mark0263** [comment]
I'm debugging this one - I don't see anything that jumps out as the issue.  Hopefully I'll have a fix soon.

**Comment by AlexL777** [comment]
Ok, thank you for spending your time in it. I will have patience.

**Comment by mark0263** [comment]
I think I see the issue - Do you have Allow stemming words set to True in the configuration?  The stemming support is very poor and I think that is what is causing the issue.  Set this option to False, then rescan the tags from the Tag Admin screen - I think that will fix the problem. 

It is documented that this setting does not work well - from the wiki:

The stemming feature is still not perfect. For example, 'Firefox' is stemmed into 'Firefoxi'. So, I don't recommend you set Allow Stemming Words to true for the time being (and forever, maybe).

I think I will remove the option in the next release.

**Comment by AlexL777** [comment]
Thanks for the quick clarification of this issue. You had been right. It was exactly that and after I followed your hints, everything has worked again. Yes, sometimes it is so and such issues are there :smile:

**Comment by mark0263** [comment]
Excellent! Glad we got it figured out . I'll go ahead and close this issue - if anything new pops up, please open a new issue.

Thanks!
Mark
