### ISSUE TITLE
How can I disable the slider with the "CMS"-Theme

### ISSUE THREAD

**Issue by AlexL777** [glFusion/glfusion#235]
Hello Developers,

I would like to put the slider in the front end on inactive with the new "CMS" themes.

What options are there and where can I find it in the backend?

Thanks in advance.

**Comment by walterrowe** [comment]
Do you mean the default content that gets installed with the system? There are several static pages and stories you can disable in the Pages and Stories admin screens (Command & Control > Pages, Command & Control > Stories).

**Comment by mark0263** [comment]
The sample rotator is a static page - so go into Command & Control -> Pages, look for the page called Rotator Example - edit it and either turn off the center block open or set the page Enabled = No

**Comment by AlexL777** [comment]
Thank you for your quick help. I have now been able to realize it.

You can close the issue now.

If you have any questions, please contact the community here.
