### ISSUE TITLE
Standard and 3rd Party Authentication Services

### ISSUE THREAD

**Issue by walterrowe** [glFusion/glfusion#236]
When standard (glfusion native) AND oauth and/or other authentication method(s) are enabled, the login panels give a drop down to select which service the user wants to use to authenticate. By default the standard (native) service is listed first and thus is the default. The user must explicitly choose one of the other services in order to use one of them. I submitted a pull request (https://github.com/glFusion/glfusion/pull/234) that makes the standard (native) service always come last in the drop down so it is never the default when other services are configured. See the comments to my pull request that show screen shots.

I have a site where only one account uses the standard service to login in (site admin). All other users are using Active Directory to authenticate. I want glfusion to default to Active Directory as the authentication service and force me as site admin to choose the standard (native) authentication service so users don't have to choose a login method. They just come to the site, type in their user ID and password, and press enter. The site defaults to Active Directory on their behalf.

Do others think this is useful?

**Comment by mark0263** [comment]
I have added an option to specify whether the local auth will display before or after 3rd party modules. b9d29852876929c9a37f6b50e6183b1752b8b6cf
