### ISSUE TITLE
Forum bug

### ISSUE THREAD

**Issue by matrox66** [glFusion/glfusion#240]
I was searching "calendar Icon" in glfusion.org Forum and found 5 entrys

The last two shown with 0 Views and 0 Replies, but the have Replies and Views...

**Comment by mark0263** [comment]
What is happening is that the parent topic id is the one that has the views counter incremented. There are a couple of options to addressing this:

1. When a topic is directly accessed (i.e.; search) - increment the views counter for the actual topic id.

2. When displaying search results (both internal to the forum and using glFusion search), use the parent id's views and reply counters.

I prefer option #2 - but it will add some additional DB queries, so I want to validate that this can be done efficiently.

Anyone else have any ideas or thoughts?

**Comment by mark0263** [comment]
Looks like option #2 is workable and it should resolve the issue.

**Comment by mark0263** [comment]
Implemented option #2 above.
