### ISSUE TITLE
Add Sort Parameters to Headlines Autotag

### ISSUE THREAD

**Issue by buddilla** [glFusion/glfusion#241]
add a sort parameter for date / views / rating and another parameter for ascending / descending

note: this is a reminder for Lord Mark Master of the Great Empire of glFusion. LOL

**Comment by mark0263** [comment]
I've done the initial change and committed - take a look.

Outstanding question - currently the query forces all featured articles to the top, regardless of the other sort or order parameter - this might not be the best approach.

I'm thinking of making the default to be featured/date/descending - if it is overwritten using the sort: parameter - then just sort by whatever is specified. 

Thoughts?

**Comment by buddilla** [comment]
I like your idea but headlines already has a featured option how will that be affected?

**Comment by mark0263** [comment]
There is a featured parameter - 0 = show all, 1 = only featured, 2 = all except featured. Prior to this feature request - if featured:0 (default value), headlines would pull all articles sorted by featured first, then by date. 

With the new sort: parameter - I've added the following:
* date
* views
* rating
* featured (implies date too) - this emulates the old default

If sort:featured - it will pull featured first, then the remaining sorted by date

**Comment by mark0263** [comment]
Closing issue as this was implemented.
