### ISSUE TITLE
Add Uikit Text Classes to Ckeditor

### ISSUE THREAD

**Issue by buddilla** [glFusion/glfusion#243]
Override ckeditors text justifications with uikits. 

for example:
ckeditor uses
style="text-align:center;"

It should be:
class="uk-text-center"

I tried doing this myself and I know it can be done. I just couldn't figure it out.

classes that should be included:
uk-text-left
uk-text-center
uk-text-right
uk-text-justify

Justify is part of the advanced ckeditor but should be part of basic and standard.

**Comment by mark0263** [comment]
Prefer to keep the styles as-is - allows better portability if another framework is used or no framework at all is used.
