### ISSUE TITLE
path admin/install is hardcoded

### ISSUE THREAD

**Issue by walterrowe** [glFusion/glfusion#248]
The path "admin/install" is hard coded in the following:

- private/system/lib-glfusion.php ... glfusion_UpgradeCheck() and glfusion_SecurityCheck()
- private/system/language ($LANG01[500] all language files)
- public_html/admin/sectest.php ... checkInstallDir()

Should we have a $CONF['path_admin'] like we have a $CONF['path_html']?

Our website security checker (WebInspect) looks for admin paths so I changed my public_html/admin to public_html/mgt. If I remove public_html/admin/install, but leave public_html/mgt/install, the glfusion security checker does not catch it when it should.

I am running a fresh pull from today from the develop branch.

**Comment by mark0263** [comment]
There are several places where the /admin/ path is hard coded or expected (plugins.php, lib-plugins, lib-glfusion, installation, upgrade routines and several plugins). I'll agree that having a configurable site admin url option without a corresponding path option is pretty useless (but that's what we inherited when we forked). Adding a configuration option for the path is a pretty significant effort (finding and fixing and testing).  Help me understand the value - I get that /admin/ is a common path so security tools and script kiddies will target it. Renaming it could provide some value, but does it provide enough return for the level of effort to implement / maintain?

**Comment by walterrowe** [comment]
The security check for whether admin/install reports incorrectly. I use public_html/mgt instead of admin. If I leave the install directory in there, glfusion does not complain. If I make an empty admin/install it does complain. This checking and error reporting is incorrect. Whether or not you explicitly create a path_admin var in $CONF, this error checking needs correcting and the hard coded language files need to use a variable to report the correct path.

**Comment by walterrowe** [comment]
The admin path doesn't have to be configurable, but it should be computed accurately so that the security checks look for the correct path and the ensuing errors report the correct path. Regardless of what I call "admin", glfusion should find 'path_admin'/install and warn me that it should be removed. It is no more secure under an alternate path than it is under the default admin/install path. Since we have an admin_url, computing the correct install dir path should be trivial if we assume that install is always in the path_admin. Take the tail of the admin_url, add it to path_html, and add install. No? It appears the code already tries to do this in one place.

**Comment by mark0263** [comment]
Initial commit done to support customizable admin paths (65798dd91925bfbf8c8e6a1a54dbe20b3cba1638) will need some additional testing to ensure it is all correct - validate new installs / upgrades / plugin uploads

**Comment by mark0263** [comment]
New install testing complete.

**Comment by walterrowe** [comment]
I wrote a simple test script myself to see if I could party the admin URL and paste it together with the HTML path. In my code I account for trailing slash in the HTML path and in the URL admin path. Don't know if this will be useful as you review what you've already done.

You can use "php -f <filename>" to run the code below after copying it into <filename>.

The output looks like this:

```
wrowe-imac:~ wrowe$ php -f test.php 
 path_html = [/path/to/html/]
 url_admin = [https://my.site.dom/admin/]
path_admin = []
path_admin = [/path/to/html/admin/]

 path_html = [/path/to/html/]
 url_admin = [https://my.site.dom/admin]
path_admin = []
path_admin = [/path/to/html/admin/]
wrowe-imac:~ wrowe$ 
```


```
<?php

$path_html='/path/to/html/';
$path_admin='';

$url_admin='https://my.site.dom/admin/';

printf (" path_html = [%s]\n", $path_html);
printf (" url_admin = [%s]\n", $url_admin);
printf ("path_admin = [%s]\n", $path_admin);

// account for potential trailing slash in HTML path
if (strlen($path_html)-1 == strrpos($path_html,"/")) {
        $slash = "";
} else {
        $slash = "/";
}

// account for trailing slash in admin URL
if (strlen($url_admin)-1 == strrpos($url_admin,"/")) {
        // url_admin ends in / so accomodate that in regexp for $2
        $path_admin = $path_html . $slash . preg_replace("/(.*\/)(.*\/)/","$2",$url_admin);
} else {
        // url_admin does not end in / so do not accomodate that in regexp for $2
        $path_admin = $path_html . $slash . preg_replace("/(.*\/)(.*)/","$2",$url_admin) . "/";
}

printf ("path_admin = [%s]\n", $path_admin);

$url_admin='https://my.site.dom/admin';
$path_admin='';

printf ("\n path_html = [%s]\n", $path_html);
printf (" url_admin = [%s]\n", $url_admin);
printf ("path_admin = [%s]\n", $path_admin);

if (strlen($url_admin)-1 == strrpos($url_admin,"/")) {
        // url_admin ends in / so accomodate that in regexp for $2
        $path_admin = $path_html . $slash . preg_replace("/(.*\/)(.*\/)/","$2",$url_admin);
} else {
        // url_admin does not end in / so do not accomodate that in regexp for $2
        $path_admin = $path_html . $slash . preg_replace("/(.*\/)(.*)/","$2",$url_admin) . "/";
}

printf ("path_admin = [%s]\n", $path_admin);

php?>

```

**Comment by walterrowe** [comment]
Installed the commit and tested. Works like a charm. Thanks!

**Comment by walterrowe** [comment]
Look at line 141 in lib-common.php. If you are looking for a trailing slash, strrpos() will return a number equal to strlen() - 1, not strlen(), based on my testing with the script above.

**Comment by mark0263** [comment]
You are correct - I'll get that fixed.  Thx!

**Comment by mark0263** [comment]
All references to admin should now be by either site_admin_url or path_admin
