### ISSUE TITLE
Add "on frontpage until" date/time for stories

### ISSUE THREAD

**Issue by leegarner** [glFusion/glfusion#257]
The only way to have a story display on the front page until a specific time is to enable auto-archiving. Then I often have to go back through the archive, disable that function and change the topic back to the original.

An extra date/time field for stories, or convert the existing one, so stories can be shown on the front page until a certain time and then not show, but left in their topics.

Show on frontpage:  [] Yes  [] No  [] Until _____________

Maybe alter and leverage the existing binary field to a datetime field, where
"yes" = "9999-12-31 23:59:59", 
"no" = "0000-00-00 00:00:00", and
"until" = user-supplied datetime

Add "where frontpage < NOW()" to the query in index.php

**Comment by mark0263** [comment]
Done with commit 659342d9156c6c5d69df8aa9a1e7f0407f59e0a6
