### ISSUE TITLE
Add and use a global Date object to represent "today"

### ISSUE THREAD

**Issue by leegarner** [glFusion/glfusion#258]
Many SQL queries use NOW() to check for things like auto-archiving. The hosting providers database may use a different timezone than the site, so it would be nice to have the site's timezone available for use. Pushing it into the $_CONF var would make it available everywhere, or it could be a static autoloaded class.

$_CONF['_now'] = new Date('now', $_CONF['timezone']);

Then in queries like the auto-archiving, use $_CONF['_now']->toMySQL(true) instead of NOW().

**Comment by mark0263** [comment]
Should there be 2 global objects - system and user?  Some system level actions like checking for RSS feed updates should use the $_CONF['timezone'] NOW() date / time, but I can see other 'user' actions such as event blocks that might benefit from using the $_USER['tzid'] NOW() date/time. 

Thoughts?

**Comment by leegarner** [comment]
Good point. I had started trying to use user timezones in Evlist but found it complicated and didn't really work as planned. I can see where it might be useful, but on the other hand if it has limited usage it might make sense to instantiate a date with the user's TZ when needed. After using the date for a while I think the conf var might be a nice shortcut to the system date but may not add that much value over creating a date object as needed.

**Comment by mark0263** [comment]
Implemented the global date object stored in $_CONF['_now'].

Implemented in LTS branch - 7cd5071029564ebae50fa1c5645ab4c18f1beb94
Implemented in develop branch - 87e52962df7b4f7a9fa860a68b6316a5ac186e2b
