### ISSUE TITLE
Add an Author field for anonymous comment submissions

### ISSUE THREAD

**Issue by TJ-Support** [glFusion/glfusion#259]
A suggestion on comment submissions for anonymous users. It might be good to have an author field like the Forum plugin so the user can add a name which comes up next to anonymous.

**Comment by mark0263** [comment]
Implemented author field
Allow comment.moderator ability to edit for anon users only
implemented silent edit feature for admins
43c633a1c9d1a80929d8184418321f5dc1701e26
