### ISSUE TITLE
GlFusion 1.5.0 - Article ID can not be changed

### ISSUE THREAD

**Issue by AlexL777** [glFusion/glfusion#28]
Hello Developers,

I've got a problem with GlFusion 1.5.0. It runs so well, but the Article ID when creating an article, I can not change. I can already submit my individual ID, but the editor does not take over.

Maybe I need to adjust something in GlFusion system yet? I dont know. I'll show you here on a screenshot.

Can you help me maybe? Thanks in advance!

![glfusion-article-id](https://cloud.githubusercontent.com/assets/7885632/11013266/0e8248dc-8506-11e5-9dbd-5e94c6c288a1.jpg)

**Comment by mark0263** [comment]
This is the second report I've received with this problem. So far, I have not been able to re-create the issue to track down why it is happening.  Both reports have been on sites that are using non-english languages - let me look into this and see if I can resolve.  Thanks for the comment!

**Comment by mark0263** [comment]
Are you able to type in a different ID?  When it saves, does it go back to the original ID?

**Comment by AlexL777** [comment]
Yes, I have tried to forgive my own ID but when I save the article, then the original ID reappears.

**Comment by mark0263** [comment]
What is the exact ID you are entering - maybe there is something glFusion doesn't like about the text - if you can give me the exact example, maybe I can duplicate the issue.

**Comment by AlexL777** [comment]
OK, that's this article http://wpzweinull.ch/cms/glfusion/article.php/2015110703553815

And the ID should be similar to the title of the article: fuer-facebook-fans-eine-facebook-blog-parade-auf-internetblogger-de

If this ID is too long? I could enter into the field with the ID is at least that.

**Comment by mark0263** [comment]
Excellent!  I can duplicate the problem.  I think you are correct, it is too long, but I'll validate and also update the code to ensure it handles items that are too long more appropriately.

**Comment by mark0263** [comment]
Confirmed, the maximum length allowed for the story ID is 40 characters.

**Comment by AlexL777** [comment]
Thank you, it has now worked well and my new ID is: facebook-blogparade

Thus, it seems to be working. So the ID was much too long. Then I make time on it that I can take shorter Article ID.

**Comment by mark0263** [comment]
I'm looking at expanding the ID to 128 characters.

**Comment by AlexL777** [comment]
Yes, that would be very useful!

**Comment by mark0263** [comment]
Expanded story id (and link id, poll id and staticpage id) to 128 bytes - fd3aca8196ce125e63b11104c7cb87501d633069
