### ISSUE TITLE
Allow icons in staticpage label

### ISSUE THREAD

**Issue by matrox66** [glFusion/glfusion#323]
Change line 341 in /plugin/staticpages/services.inc.php

`        $sp_label = strip_tags ($sp_label);`
to
`        $sp_label = strip_tags ($sp_label,'<i>');`

% maybe also for title

**Comment by mark0263** [comment]
Awesome suggestion!  I'll get this into the next minor release!

**Comment by mark0263** [comment]
Implemented with 562bcb79a19fe2d47185bb5ab9cfb36b553b18a7
