### ISSUE TITLE
Alignment classes missing from CMS theme

### ISSUE THREAD

**Issue by leegarner** [glFusion/glfusion#33]
I've been using the alignment classes "aligncenter", "alignright" and "alignleft" rather than inline style tags, but these classes aren't in the CMS theme. If there's not a particular reason for that it would be nice to include them for compatitibility. Previous themes had several classes together; I don't know if those are needed any more.

.alignright {
text-align:right;
}
.gl_user-menu-left,.alignleft {
text-align:left;
}
.aligncenter,.edit-perm-down,.pagenav,.row_center td {
text-align:center;
}

**Comment by mark0263** [comment]
I'll get the align* classes into the next incremental release (which should be by the weekend - goal is to do small incremental updates each week as needed).  Also need to go through the old style sheet and see if there are any other general purpose classes that should be added.

**Comment by mark0263** [comment]
Added alignleft, alignright, and aligncenter - 9446556d8951864e29f1e890d6564f2156f81f8e
Still need to validate if there are other utility type classes to add...

**Comment by leegarner** [comment]
LOL, I thought of it as an enhancement, didn't notice you added the "bug" label.  Thanks, If I find others I'll keep a list and add them here.

**Comment by walterrowe** [comment]
I think documentation should be provided that tells people how to port their “old” classes to the corresponding correct UIKit classes. We want to continue the pursuit of making everything UIKit clean, right?

Walter

**Comment by leegarner** [comment]
True, but until everyone changes their site templates to one that's based
on Uikit there will be functionality lost. As it is I'm checking for
$_SYSTEM['disable_mootools'] or $_SYSTEM['disable_jquery'] to determine
which JS & CSS to load, and whether to call window.addEvent(load) or
$(document).ready().

I can always use 'style="text-align:center;"' in templates (and have many
times) but my preference is to centralize CSS in style.css as much as
possible. Of course I can always add my own CSS wrappers but it makes sense
to ensure that all the existing CSS has equivalents in Uikit. Ideally a
webmaster can simply choose Nouveau or CMS in the theme switcher and
they'll just work.

**Comment by mark0263** [comment]
One of the reasons why this release cycle is labeled 1.5.x instead of 2.0 is that I consider this a transition release - we're moving from the old to the new UIKIT framework. I want to do this in a manner that provides our users the opportunity to make the trip with us, but somewhat at their own pace.  I think it is perfectly acceptable for utility classes like these to be added to the new themes - I will create an area in the style sheet to denote that these are compatibility classes to allow for their removal at some point.

**Comment by walterrowe** [comment]
I can buy into that. Does this mean you will shoot for 2.0 being 100% UIKit including all the plugins?

Walter

**Comment by mark0263** [comment]
That would be the goal!
