### ISSUE TITLE
Cannot install new Plugins under MariaDB Engine and with PHP 7.2

### ISSUE THREAD

**Issue by AlexL777** [glFusion/glfusion#341]
Hello Developers,

i cannot install new Glfusion Plugins. I use MariaDB 10.2.x and PHP 7.2 for my Project. 

In the Error-Logs i see this:

    15 Okt 2018 16:34:44 CDT - xxxxxxxxxxxx: 23000: Duplicate entry 'sg_main' for key 'name' in /xxxxxxxxxxxxxxxx/glfusion.cms-blogger.eu/private/system/classes/config.class.php:1161 SQL in question: INSERT INTO gl_conf_values (name, value, type, subgroup, group_name, selectionArray, sort_order, fieldset, default_value) VALUES ('sg_main','N;','subgroup',0,'faq',-1,0,0,'N;')   

This error occurs with every new plugin installation. I wanted to install DokuWiki or Tags, but I always got error messages during the plugin installation.

How can it be fixed or is it specifically MariaDB Database Engine. I have often had bad experiences with MariaDB. My Shared hosting doesn't have anything else, so I have to get by like this.

I use the latest Glfusion-Version!

**Comment by mark0263** [comment]
It appears you have an Unique Index called 'name' on the 'name' field of the gl_conf_values table. I'm not sure how that index would have been created, glFusion doesn't index that field as it is designed to have duplicates.  The quick and easy fix, if you are comfortable using a tool like phpMyAdmin is to drop the index on the name field of the gl_conf_values table.

As for MariaDB - I use it on one of my development system to ensure everything works with it as it should - haven't had any issues, so it should work fine.

**Comment by leegarner** [comment]
Try running "show create table gl_conf_values" in phpMyAdmin or the MySQL console. There should be no key on that table.

**Comment by AlexL777** [comment]
Thanks for your Hints. 

Yes, right, I had added Unique Index to the database structure because I didn't see any buttons for editing and deleting. So I thought I was doing it right.

Now I could install DokuWiki and tags, but the sitemap can't be installed.

Error-log shows that the table already exists, but not in the database. And during the sitemap installation I am redirected and then Error 500 appears on the page. What am I doing wrong?

Please test Sitemap Install on a test project. Thanks, maybe I'm doing something wrong.

**Comment by mark0263** [comment]
If you want to create an index on the conf_values table to allow editing (which we do not actually recommend since the configuration values are serialized and very difficult to edit by hand) - you would create the index on the ID field.   We recommend you use [fusionrescue](https://www.glfusion.org/wiki/glfusion:fusionrescue) to edit configuration settings.

For Sitemap - try installing one more time - if there was an old table or other DB entries left over from a previous install or failed install - the plugin installer will try to remove them after the failure.  So try to install one more time.  If you are still getting the 500 error - check for an error_log file in the public_html/admin/plugins/sitemap/ directory - it may give us a better clue as to the problem.

**Comment by AlexL777** [comment]
OK, thanks for the hints. My Local error_log showing this.

`[15-Oct-2018 23:01:13 UTC] PHP Fatal error:  Uncaught Error: Class 'Sitemap\Cache' not found in /xxxxxxxxxxxxxxxxxxx/glfusion.cms-blogger.eu/private/plugins/sitemap/autoinstall.php:116
Stack trace:
#0 /xxxxxxxxxxxxx/glfusion.cms-blogger.eu/private/system/lib-plugins.php(243): plugin_autouninstall_sitemap()
#1 /xxxxxxxxxxxxxxxxxxx/glfusion.cms-blogger.eu/private/system/lib-install.php(353): PLG_uninstall('sitemap')
#2 /xxxxxxxxxxxxxxxxxx/glfusion.cms-blogger.eu/private/system/lib-install.php(439): INSTALLER_fail('sitemap', Array)
#3 /xxxxxxxxxxxxxxxxxxx/glfusion.cms-blogger.eu/private/plugins/sitemap/autoinstall.php(98): INSTALLER_install(Array)
#4 /xxxxxxxxxxxxxxxxxxxx/glfusion.cms-blogger.eu/admin/plugins/sitemap/install.php(62): plugin_install_sitemap()
#5 {main}
  thrown in /xxxxxxxxxxxxxxxxxx/glfusion.cms-blogger.eu/private/plugins/sitemap/autoinstall.php on line 116`

**Comment by mark0263** [comment]
I've updated the Sitemap code base with a fix for the above error:

[Sitemap Repository](https://github.com/glFusion/sitemap)

**Comment by AlexL777** [comment]
Thanks for This, Mark! my Problem is now solved with you changes in the repository.

**Comment by mark0263** [comment]
Awesome - going to close this one out.

Thanks!
