### ISSUE TITLE
Ckeditor is not displayed when creating an article - what to do?

### ISSUE THREAD

**Issue by AlexL777** [glFusion/glfusion#342]
Hello Developers,

I have a problem with the Ckeditor, which is not displayed when creating an article. 

For static pages and FAQs the editor is shown, but only for articles not. 

I've already done all kinds of options, but without success. 

What am I doing wrong?

Thanks in advance.

**Comment by mark0263** [comment]
Couple of things to check

1) Make sure you are selecting the Visual Button on the story edit screen to show the CKEditor.

2) Right click on the page and select **Inspect** from the pop-up menu.  Once the Inspect window opens, select the **Console** tab.  We want to see if there are any Javascript errors listed - they will be in red - if there are - please cut / paste them in your reply and we can see what is not loading properly.

**Comment by AlexL777** [comment]
The Visual Button is not showing. 

In The Console i see this:

`story.php?edit=x:285 Uncaught SyntaxError: Unexpected identifier
activitytimer.js:27 Uncaught ReferenceError: editor_type is not defined
    at refreshTokens (activitytimer.js:27)
    at HTMLDocument.<anonymous> (activitytimer.js:6)
    at i (js.cache.js:6)
    at Object.fireWith [as resolveWith] (js.cache.js:6)
    at Function.ready (js.cache.js:6)
    at HTMLDocument.J (js.cache.js:6)`

**Comment by mark0263** [comment]
The Javascript variable **editor_type** seems to be missing. This variable is set in the storyeditor.thtml template (located in the public_html/layout/cms/admin/story/ directory).  

Is it possible that you have a custom storyeditor.thtml file that hasn't been updated?  I would look in the public_html/layout/cms/admin/story/custom/ directory.

Or it could be you have an older template file that didn't get overwritten during an upgrade.  I doubt this is the problem as this variable was added back in 2016.  

Let me know if you have a custom version of the template, or if you are using a different theme than the CMS theme.

**Comment by AlexL777** [comment]
No, I don't use a custom template for the story editor. I just uploaded the directory /private and /public_html again and did an update.

I also tried the Legacy theme, but without success. The same error is displayed in the console.

What else can I do?

**Comment by mark0263** [comment]
The JavaScript needed to make all this work is located in the /javascript/ directory off of public_html. I suspect you have an Apache rewrite rule that is redirecting /javascript/ to a different location.  I have seen this in the past where default installs of Apache include this rewrite rule.  A good way to test this is to try and access one of the Javascript files included with glFusion directly - i.e.; https://yoursitehere.com/javascript/resetrating.js  - if this fails - it is either the files are missing or you have a redirect in place that is causing /javascript/ to look somewhere else.  We create a [FAQ about this](https://www.glfusion.org/faq/index.php/11) - I think that is what is causing the issue.

**Comment by AlexL777** [comment]
I moved my Glfusion site to the root server and can't log in under https.

Console shows "mixed content", which comes from the rotator block, but you can't deactivate this block from outside or am I mistaken?

I know from experience that SSL has to be 100% there, otherwise you can't log in.

How can I solve this, because it also has something to do with this issue to deactivate the javascript-common module on the root server.

In Shared Hosting the webhost is not allowed to do it. Very unfortunate.

Thanks in advance.

**Comment by mark0263** [comment]
I doubt it is the mixed content that is preventing the login - it is probably either the Cookie domain or Cookie path that is causing the problem.  You can use [fusionrescue](https://www.glfusion.org/wiki/glfusion:fusionrescue) to edit those fields outside of glFusion.

Also, when you move a site to a new URL - sometimes the browser will cache the cookies from the old path - make sure you completely clear all cookies and cache in the browser - I have seen this resolve login problem as well.

**Comment by AlexL777** [comment]
After a few hours of trying I found out why no login was possible. I set cookie_domain to "true" and that was the reason.

But with the story editor in articles it still doesn't work. I was able to access the JS file you mentioned above with the browser. Everything seems to be ok and under Plesk Onyx in Centos 7.5 I have no javascript-common module at all. I just checked that.

It must still be due to something. On static pages and in the forum the visual tab is displayed. 

Hm...

**Comment by mark0263** [comment]
Go ahead and clear the glFusion cache and your browsers cache - then load the story editor - do the right click - Inspect thing again and let's see if we have the same or different JS errors.

**Comment by AlexL777** [comment]
My Problem is now solved. 

I no longer hesitated with the complete reinstallation. The story editor is now displayed on articles. Why look for errors, because it could not be found.

I tried everything. Hence the new installation. Now everything seems to be ok at first sight and if you have further questions I will contact you again.

Thanks for your time.

**Comment by mark0263** [comment]
Very good - I'll close this one out - we're here if you run into anything.
