### ISSUE TITLE
Configuration Sections are no longer in order with version 2.0

### ISSUE THREAD

**Issue by TJ-Support** [glFusion/glfusion#358]
In the Admin/Configuration settings the Configuration Sections are not in order with version 2.0

**Comment by TJ-Support** [comment]
I found out why...
https://github.com/glFusion/glfusion/commit/e66c27e19567bfdc5fa259d34eb6c1f2b0e9bd28

**Comment by mark0263** [comment]
Fixed with commit 99f1ba89b06e746e993c1147e827895fec7cb911
