### ISSUE TITLE
How can you remove NoFollow attribute from the Forum signature - glFusion 1.5.1

### ISSUE THREAD

**Issue by AlexL777** [glFusion/glfusion#36]
Hello Developers,

I have an interesting question and although I would like the forum Signature at glFusion 1.5.1
have no NoFollow links.

How can I remove nofollow? How to remove it in the forum, I know, but in the signature are still nofollow links. In my forum post is no one but me, so Google must follow all links.

Looking forward to your help.

![glfusion-forum-signatur-nofollow-links](https://cloud.githubusercontent.com/assets/7885632/11169908/f81eb1dc-8bc4-11e5-9a9e-ced333ab90af.jpg)

**Comment by mark0263** [comment]
The rel="nofollow" is hard coded in the BBCode parser - you would have to modify the PHP code to remove it.

**Comment by AlexL777** [comment]
Many thanks for your response. Ok, then I can live with nofollow in the signature.

**Comment by mark0263** [comment]
I'll look into adding a configuration option for this.

**Comment by AlexL777** [comment]
Thank you! That would be very useful for all users and I am alone in my glFusion forum and no one else can post, Google can evaluate my own signature links :)
