### ISSUE TITLE
installation error "Unable to connect to database"

### ISSUE THREAD

**Issue by GaneshKandu** [glFusion/glfusion#38]
![aesfsfaf](https://cloud.githubusercontent.com/assets/12833130/11209985/cf64c2ea-8d4a-11e5-80ab-5456c478e067.png)
I am istalling glFusion getting error on "Content & Plugins" step,
installer creates 43 table successfully 
i have tried all combination of mysql, mysql with innoDB,mysqli with and without UTF-8
i am using
PHP Version 5.3.29
Apache/2.2.31 (Unix)
mysql version: 5.5.45

**Comment by mark0263** [comment]
Look at the private/logs/error.log to see if there are any details in the log to give us a clue.

**Comment by GaneshKandu** [comment]
private/logs/error.log contain only this " *** dummy entry *** "

**Comment by walterrowe** [comment]
That is a good thing. That means no errors.

Walter

**Comment by GaneshKandu** [comment]
I am getting this error every time when i am trying installation
and its not getting installed successfully

**Comment by walterrowe** [comment]
Does the database exist? You have to create the database and DB login credentials in your MySQL database first, then give that info in the GLF install screen.

**Comment by mark0263** [comment]
There is obviously an error - I suspect it may be a corrupted file, but haven't yet determined where the failure is happening.  2 more items will help me track it down:
 1. What is the last table name that is created?
 2. Do any of the tables have data in them?

I'm trying to identify exactly where in the process it is failing.

**Comment by GaneshKandu** [comment]
These are tables
and only gl_sessions having one row
gl_access
gl_article_images
gl_autotag_perm
gl_autotag_usage
gl_autotags
gl_blocks
gl_commentcodes
gl_commentedits
gl_commentmodes
gl_comments
gl_conf_values
gl_cookiecodes
gl_dateformats
gl_featurecodes
gl_features
gl_frontpagecodes
gl_group_assignments
gl_groups
gl_maillist
gl_menu
gl_menu_elements
gl_pingservice
gl_plugins
gl_postmodes
gl_rating
gl_rating_votes
gl_sessions
gl_sortcodes
gl_speedlimit
gl_statuscodes
gl_stories
gl_storysubmission
gl_syndication
gl_tokens
gl_topics
gl_trackback
gl_trackbackcodes
gl_usercomment
gl_userindex
gl_userinfo
gl_userprefs
gl_users
gl_vars

**Comment by mark0263** [comment]
It is making it through the creating of all the core tables, appears to be failing on the initial data population.  I'm running through some testing scenarios to pin point the where and how it is failing for you.  It may be another day before I get it tracked down.

**Comment by GaneshKandu** [comment]
I tried to install on wamp and its successfully installed but not able to install on linux machine 
and getting 404 error 
installing in sub directory  

"NetworkError: 404 Not Found - /images/library/Image/moorotator1.jpg"
moorotator1.jpg
"NetworkError: 404 Not Found - /images/library/Image/moorotator2.jpg"
moorotator2.jpg
"NetworkError: 404 Not Found - /images/library/Image/moorotator3.jpg"
moorotator3.jpg
"NetworkError: 404 Not Found - /images/library/Image/moorotator4.jpg"
moorotator4.jpg
"NetworkError: 404 Not Found - /images/library/Image/moorotator5.jpg"
moorotator5.jpg
"NetworkError: 404 Not Found - /images/library/Image/moorotator2.jpg"
moorotator2.jpg
"NetworkError: 404 Not Found - /images/library/Image/moorotator4.jpg"
moorotator4.jpg
"NetworkError: 404 Not Found - /images/library/Image/moorotator5.jpg"
moorotator5.jpg
"NetworkError: 404 Not Found - /images/library/Image/moorotator3.jpg"
moorotator3.jpg
2
"NetworkError: 404 Not Found - /images/library/Image/moorotator1.jpg"
moorotator1.jpg
"NetworkError: 404 Not Found - /images/library/Image/moorotator5.jpg"

existing image location is
/glfusion/images/library/Image/moorotator1.jpg

**Comment by mark0263** [comment]
Looks like the 404 errors are a result of installing glFusion in a sub-directory off the web-root.  I've opened an issue / fix for this so it sets the directory properly on install.
