### ISSUE TITLE
Odd line break before ellipses in COM_truncateHTML()

### ISSUE THREAD

**Issue by leegarner** [glFusion/glfusion#382]
Very minor issue, but under some circumstances there may be a line break between the text and ellipses after calling COM_truncateHTML(), which looks odd in the display.

I've tested using rtrim() on line 5935 of lib-common.php and it seems to fix the issue.
``` 
   if ($printedLength < $maxLength && $position < strlen($html))
        $retval .= rtrim(substr($html, $position, $maxLength - $printedLength));
```

**Comment by mark0263** [comment]
Implemented with commit cb26a9c
