### ISSUE TITLE
Dokuwiki doesn't provide author name in getiteminfo function

### ISSUE THREAD

**Issue by leegarner** [glFusion/glfusion#410]
When indexing Dokuwiki pages, the author name isn't returned. I don't know where the repo is for the dokuwiki plugin, but adding these lines to plugin_getiteminfo_dokuwiki() seems to fix it. The page owner is then shown as the author.

```
531d524
<         $meta = pageInfo($item['id'], $item['rev']);
593,599d585
<                 case 'author_name':
<                     if (isset($meta['userinfo']['name'])) {
<                         $props[$p] = $meta['userinfo']['name'];
<                     } else {
<                         $props[$p] = 'Unknown';
<                     }
<                     break;
```

**Comment by mark0263** [comment]
Fix implemented - also added support for the glFusion config setting of show_fullname to return the proper username or full name based on glFusion's configuration.

Fix has been implemented in the dokuwiki repository at glLabs (code.glfusion.org)
