### ISSUE TITLE
Possibly change theme storage from cookie to session

### ISSUE THREAD

**Issue by leegarner** [glFusion/glfusion#418]
This is probably only an issue in the real world when testing, but if user-selected themes are allowed the anonymous user retains the logged-in user's them after logging out.

To clarify, if the default theme is "CMS" and a user has "Theme1" selected, then after the user logs out the browser continues to user "Theme1" instead of switching back to CMS. Saving the theme name in the session fixes this.

**Comment by mark0263** [comment]
Question - I have no real preference one way or the other - but the reason it is stored in the cookie is to allow returning users to see their selected theme prior to login.  Moving to a session variable would make it so the selected is theme is only shown once logged in, always reverting back to the site default theme when logging out.  

Moving to a session variable is pretty trivial and also requires an update to vThemes to support - I can implement pretty quickly if you haven't already started.

**Comment by walterrowe** [comment]
Is it also possible to simply unset (delete) the theme cookie on logout?

Walter

**Comment by mark0263** [comment]
Deleting the cookie would work as well.  Saving the theme in either a cookie or a session variable really only supports the vThemes plugin - allowing you to select a different active theme but not updating account profile permanently.  

The original intent was to allow applying the user selected theme after log out. So removing the cookie or switching to session variables defeats the original intent (which again I have no real preference as I don't think most sites have multiple themes to choose from).

**Comment by walterrowe** [comment]
Question for you both .. since this is really browser specific .. how often is it likely one user would follow another in the same browser on the same system and visit the same website?

**Comment by leegarner** [comment]
That's what I was thinking when I mentioned that it's probably only an
issue when testing. Now that you mention the theme switcher it makes sense
to do it with the cookie, I'd forgotten about that. And naturally sites
that have one theme (probably the vast majority). Now that I know this,
it's probably not worth bothering with. I've been simply using 2 browsers
or deleting the cookie, which works for me.

Along the multiple-theme note though, one thing I've had to deal with is
the site logo where different themes have different header sizes and
backgrounds. The obvious solution is simply to upload a new logo and change
the header html to use it, or show the site name, etc. in the theme. It's
not like it's so difficult, but it seems like with the logo function in
Command and Control it could be easier. This is what I'm thinking of:
[image: image.png]

I don't have a lot of need for switching themes other than testing and
development, but I do see it as an option on many sites, particularly for
dark vs. light.

Thoughts?

**Comment by walterrowe** [comment]
The template logo-graphic.thtml has a hardcoded logo size. How difficult is it to allow that to be a fluid size based on the actual image size?

Here is logo-graphic.thtml ..

```
{# begin {templatelocation} #}
<a class="uk-navbar-brand tm-navbar-brand uk-hidden-small" href="{site_url}" itemprop="url">
<img itemprop="logo" class="uk-margin uk-margin-remove" src="{site_logo}" width="140" height="30" title="{site_name}" alt="{site_name}">
</a>
{# end {templatelocation} #}
```

In contrast, logo-text.thtml has no size information for the space it consumes.

Also looking in style.css I see that tm-header has a hard-coded 55px height.

**Comment by walterrowe** [comment]
The template logo-graphic.thtml has a hardcoded logo size. How difficult is it to allow that to be a fluid size based on the actual image size?

Here is logo-graphic.thtml

```
{# begin {templatelocation} #}
<a class="uk-navbar-brand tm-navbar-brand uk-hidden-small" href="{site_url}" itemprop="url">
<img itemprop="logo" class="uk-margin uk-margin-remove" src="{site_logo}" width="140" height="30" title="{site_name}" alt="{site_name}">
</a>
{# end {templatelocation} #}
```

In contrast, logo-text.thtml has no size information for the space it consumes.

Also looking in style.css I see that tm-header has a hard-coded 55px height.

**Comment by walterrowe** [comment]
Does this subject really belong under the UIKit 3 topic?

**Comment by leegarner** [comment]
At the moment the header and logo size are fixed and would normally be set
by the theme, since each theme would have its own CSS. As it is, each theme
has its own style.css that can be updated. The image width and height could
be set that way also by just adding a ".tm-logo" class or something like
that. It's be a good idea.

**Comment by leegarner** [comment]
Actually it's not uikit3-specific, but I think this issue can be closed as the theme name storage doesn't need to be changed.

**Comment by mark0263** [comment]
Closing - it was decided to leave as-is.
