### ISSUE TITLE
Implement a simple database search and replace

### ISSUE THREAD

**Issue by mark0263** [glFusion/glfusion#429]
Under the Database Administration area - implement a simple search and replace to allow site owners to easily update URLs, etc. 

Possible issues to think thru....

- Should we allow user to select which tables to process?
- Should we allow user to select specific columns

If we process at the table level - doing a search replace of "glFusion" to "really Cool glFusion" could update fields that we do not want to be updated - such as the topic_id field on a story.

**Comment by leegarner** [comment]
I think at least select specific tables, and those tables can have fixed column selections, e.g. "introtext" and "bodytext" for stories, "sp_content" for staticpages, "content" for blocks, etc.. Changing a topic is easy to do in the Topic admin.

I think that it would be easy to get into the weeds trying to anticipate all possibilities.

**Comment by mark0263** [comment]
Agreed - I think I'll create a new PLG function so plugins can return information about their 'content' areas.

Maybe plugin_getContentTableInfo_<plugin_name>();

It would return something like:

```
       array(
            'table_name' => 'gl_stories',
            'primary_key' => 'id',
            'columns'    => array(
                'title',
                'subtitle',
                'introtext',
                'bodytext'
            )
        );
```

This allows the search/replace function to focus only on those tables and the specific columns that would contain content.

Thoughts?

**Comment by leegarner** [comment]
I like it. Between allowing a selection of tables, and only acting on "content" fields, it should be about as safe as it can be. Obviously there should be a BIG warning to back up the database, I think even automatically launch the built-in backup prior to making the changes.

**Comment by walterrowe** [comment]
And since you know the specific tables you could automatically run a special backup on just those tables.

Walter

**Comment by mark0263** [comment]
I've checked in the initial version - still some cleanup to do but it is functional.

**Comment by leegarner** [comment]
Very cool. One thought would be to have a note at the bottom of the table
after a dry run saying "This is a dry run, click here to execute" and a
button to pass all the args except "dry_run" to do it for real.

**Comment by mark0263** [comment]
Good idea - I've modified it a little so the Dry Run is forced - then from the Dry Run Results screen you can execute, edit or start over.  Cleaned up the diff dialog a bit as well - a little better formatting and removed all the non-modified lines to make it cleaner.

I think it is about done - unless anyone has some feedback that I need to address.

**Comment by mark0263** [comment]
Implemented in glFusion v2
