### ISSUE TITLE
Automatically set the framework var in templates, similar to site_url

### ISSUE THREAD

**Issue by leegarner** [glFusion/glfusion#451]
Creating an issue for posterity... would it make sense to set the value of $_SYSTEM['framework'] automatically in templates? CMS defines this as "uikit" so in modern themes it should be set (or empty). This would help when using a framework that just doesn't support the same features but otherwise the template changes are small. Example for uikit2 vs uikit3, where most classes don't conflict but the progress bar is just different:
```
{!!if {framework} == 'uikit3' !!}
        <progress class="uk-progress tooltip" title="{$LANG_QUIZ['question']} {q_num} of {num_q}" max="100" value="{pct}"></progress>
{!else}
        <div class="uk-progress">
            <div class="uk-progress-bar" style="width:{pct}%">
                {$LANG_QUIZ['question']} {q_num} of {num_q}
            </div>
        </div>
{!endif}
```

**Comment by mark0263** [comment]
Is this one ready to close?

**Comment by leegarner** [comment]
This is good to close. Commit #461 took care of it.
