### ISSUE TITLE
Delete syndication files when syndication is disabled.

### ISSUE THREAD

**Issue by leegarner** [glFusion/glfusion#468]
It seems to make sense when disabling a syndication feed to delete the related file from public_html/backend, since keeping it would continue to syndicate old data. When enabling, the file could be regenerated just as it is when editing and saving the feed.

**Comment by leegarner** [comment]
I'm wondering about another idea, which is only slightly more complex, which is to update SYND_updateFeed() and SYND_updateFeediCal() to create feed files with no data, only headers and footers. That would keep the feed valid but prevent data from being included.

**Comment by mark0263** [comment]
I know you've done a lot of work on syndication - has this one been implemented?

**Comment by leegarner** [comment]
Implemented in 5b728e9bb71d185efbe6666727bdf4be3f5fc66c

**Comment by leegarner** [comment]
I was incorrect, the file is deleted when the feed is deleted, but not when
the status changes. I submitted
https://github.com/glFusion/glfusion/pull/505 to delete or update the feed
when the status is changed.
