### ISSUE TITLE
Arbitrary user impersonation vulnerability

### ISSUE THREAD

**Issue by Topsec-bunney** [glFusion/glfusion#482]
**In the article comments，We can impersonate any user to comment，You can even impersonate a system administrator**
![chrome_KydmsyhHuD](https://user-images.githubusercontent.com/73220685/145172316-ca752a86-e90b-41b8-89f0-f389251203aa.png)
![chrome_MGW6ahjcFD](https://user-images.githubusercontent.com/73220685/145172345-11412778-b000-4805-a2b7-3dde62f1e61b.png)
![chrome_HMpO3sqwgm](https://user-images.githubusercontent.com/73220685/145172554-3d121c17-04d5-49cb-bc63-2a3973054d75.png)

**Comment by mark0263** [comment]
Thanks for the report.  This seems pretty straight forward to fix, there is an existing UniqueName call that will query the user table to determine if a username already exists, if it does, it will add a random 4 digit number to the end of the username.  So in your example, Admin would become Admin6823.

Does the community feel this is an appropriate method to prevent the impersonation?

**Comment by Topsec-bunney** [comment]
Yes, the method you said can solve this problem
