### ISSUE TITLE
glFusion CMS 1.7.9 user Login denied vulnerability

### ISSUE THREAD

**Issue by Topsec-bunney** [glFusion/glfusion#487]
We can get username on this link:
```http://192.168.255.130/glfusion1.7.9/public_html/users.php?mode=profile&uid=3```
![firefox_fIwf2EDlUU](https://user-images.githubusercontent.com/73220685/145376552-976aae00-0893-44b7-ac14-0c1e7de9233f.png)

So, attacker can get all username .

Then they can always log in to all users with the wrong password, which will prevent all users from logging in to the website normally.

![firefox_LrrbnCvHFd](https://user-images.githubusercontent.com/73220685/145376725-bde27dbe-c667-4ba4-8cf4-4b5f99998885.png)

There are two solutions:

1. set the verification code on the login page

2. The second is to display the user's nickname instead of the login name

**Comment by leegarner** [comment]
Currently the full name (could be a nickname) is shown along with the
username. I don't think it would hurt to show only the fullname, if
available, otherwise the user name.

Creating a "nickname" field is interesting, but I suspect most users will
leave it blank if allowed, or use their login names for it as well.

**Comment by leegarner** [comment]
Incidentally, it's worth mentioning that the lockout is based on failed
attempts from an IP address, not by user name. So the valid user could
still log into the site.  Unless they're sharing a public IP with the
attacker, of course.

**Comment by mark0263** [comment]
As Lee mentioned, the lockout is temporary and in-line with standard practices in performing a temporary lock out to prevent brute force attacks.  I don't see this as a vulnerability.

**Comment by mark0263** [comment]
closing as this is designed behavior
