### ISSUE TITLE
Remove Content Syndication Config vars in glFusion v2

### ISSUE THREAD

**Issue by mark0263** [glFusion/glfusion#506]
The configuration settings for content syndication seem duplicative to me.  The only one that I think **might** be worth keeping is the Enable Syndication - but I don't know that we need a configuration setting for this, you can simply delete or disable all feeds in the Content Syndication editor and that serves the same purpose.

Anyone have a good reason to keep any of the content syndication configuration settings?

**Comment by leegarner** [comment]
I agree. Each feed can be disabled or enabled at will and the support for
multiple feeds has rendered the global config obsolete IMO. I didn't look
at the number per portal block but maybe that can be added to the feed
definition also.

**Comment by mark0263** [comment]
Sounds good - I'll go ahead and remove the configuration options and update the codebase where it references there.

**Comment by leegarner** [comment]
Actually moving the portal max to the syndication table will take some
thought unless we want to leave it in the global config. The only places I
see it used is in COM_rdfImport() and WIDGET_tickerRSS(), and neither of
those know anything about the feed config. They just get the feed URL and
read X elements according to the config. We could track back to the
individual feed config based on the URL, I'm wondering if just using an
option passed to WIDGET_tickerRSS() might be the best way to control that
limit per-block.

**Comment by mark0263** [comment]
COM_rdfImport() will take the portal max from the block configuration, so that isn't an issue.
the lib-widgets - just going to hard code it to 50 for now - I will look at adding it to the options array which should be pretty simple.

**Comment by leegarner** [comment]
Sounds good. I was thinking the same, add to the options array with a
reasonable default if not set
