### ISSUE TITLE
Article feeds fail due to plugin_getiteminfo_article() not available

### ISSUE THREAD

**Issue by leegarner** [glFusion/glfusion#534]
The article RSS feed is failing because lib-article.php isn't included. One option is to add this to classes/Syndication/Feed.php:
```
if ($this->getType() == 'article') {
    USES_lib_article();
}
```
Another way is to add similar code to `PLG_getItemInfo()`, but since lib-article.php is basically just functions.inc for articles maybe it should be included in lib-common.php always.

**Comment by walterrowe** [comment]
Curiosity question .. does glfusion have any stats on how many site admins have RSS enabled? Is it still popular?

**Comment by leegarner** [comment]
I don't know about article RSS, but I use syndication for Evlist, and I was once asked for it for Shop to include in Facebook catalogs.

By the way, tracing further I see that lib-article.php is included so I'll resolve this, but there appears to be a content issue breaking the feed which I'm looking into.

**Comment by leegarner** [comment]
This actually was due to a php in an autotag class. Still don't know why it didn't affect the display of the article, but fixing the error allowed the article feed to be created.
