### ISSUE TITLE
No Admin Screen Icon for Autotag, AddThis

### ISSUE THREAD

**Issue by walterrowe** [glFusion/glfusion#56]
Note that the "Inspect Element" panel at the bottom of the screen shows styles applied to the icons for these items that force the icons to not appear.

<img width="1367" alt="glfusion-1 5 2-admin" src="https://cloud.githubusercontent.com/assets/7131288/12119242/8454dcd0-b398-11e5-8352-dec79be7d674.png">

**Comment by mark0263** [comment]
Are you running an Ad Blocker extension in your browser?  I have seen some that don't seem to like the autotag icon and block it.

**Comment by walterrowe** [comment]
I am running AdBlock, but that wouldn't add that style would it? The icons for both AutoTag and AddIt are hidden.

**Comment by mark0263** [comment]
It might - try disabling the extension and see if that solves the problem.
