### ISSUE TITLE
AutoTag and Template tags

### ISSUE THREAD

**Issue by buddilla** [glFusion/glfusion#57]
Merge autotag and template tags into single tag system so they can be used interchangeably within static pages/stories and template files.

This will also help with issue #41 https://github.com/glFusion/glfusion/issues/41

**Comment by buddilla** [comment]
This comment is a reminder that to make the tags available everywhere glfusion will need to add namespaces . 

Not to actually "Merge" but to make the template tags available in pages,stories, blocks etc.

**Comment by mark0263** [comment]
Closing as merging these 2 items is not really feasible - each has a unique use for very different purposes - template tags are specific to a template.
