### ISSUE TITLE
Menu Type Edit Disabled

### ISSUE THREAD

**Issue by buddilla** [glFusion/glfusion#58]
After saving a menu element in the menu editor as submenu, the "menu type" drop down menu is disabled from being changed when in edit mode.

edited: define issue more clearly.

**Comment by mark0263** [comment]
Fixed with commit bfb6e72c233e61fdd6f2d7debafd7de1e3bb0f1e - If the sub menu does not have any children, you can now change the element type. If the submenu has children, you cannot change the type (it would orphan the children).

**Comment by spacequad** [comment]
Downloaded and updated beta test site with latest git update as of 23 Feb, 16 with the same end results from https://www.glfusion.org/forum/viewtopic.php?showtopic=41890.
