### ISSUE TITLE
Static Page Blank

### ISSUE THREAD

**Issue by buddilla** [glFusion/glfusion#60]
Accessing a populated static page set to blank directly results in the static page id being being outputted at the top of the page and 
`<div class="uk-width-1-1 uk-container-center uk-text-center uk-clearfix">
 &nbsp;
 </div>` 
being added at the end of page. Temporary workaround is to set the static page to fill whole page of a topic or as front page.

When using render.class.php autotag hack and the static page is set to blank [link.](https://www.glfusion.org/forum/viewtopic.php?showtopic=41853) The added output is after the rendered header.thml before the staticpage content and the extra div container output is at the end of static page content before the rendered footer.thtml .

**Comment by mark0263** [comment]
Fixed with commit d8795dd252c788b9bb46a8075273ce83f4095c7d
