### ISSUE TITLE
Support for Class and alt in img Autotag

### ISSUE THREAD

**Issue by buddilla** [glFusion/glfusion#63]
Add support for img autotag to accept classes and alt descriptions and move alignment to class. format could look like this.

`
[img:imageid class:class1,class2,ect align:var src:var link:var linksrc:var alt:alternate_text]
`

output would look like this
`
<img src="/path/to/image" class="class1 class2 ect image-alignment" alt="alternate text">
`

**Comment by mark0263** [comment]
class: attribute has been committed - will look at alt next...

**Comment by mark0263** [comment]
Completed with 28b1731e5277ec38975c87c2674e2f23de18dcfd - now uses class: and tag: parameters
