### ISSUE TITLE
Forum sort order

### ISSUE THREAD

**Issue by spacequad** [glFusion/glfusion#68]
When creating or editing forum topics, the sort message on the left that states "Display After" has the opposite effect.  It actually should read "Display Before" in order for this to be factual.  However, the way it reads is the way it should be.  Fixing the underlying code that controls it, should be fixed.  This was found in the production code of 1.5.1.  Page at /admin/plugins/forum/boards.php

**Comment by mark0263** [comment]
I've been testing this and can't seem to duplicate - new forums are created in the right spot, editing always results in 'display after' as well.  Any additional information you can provide would be helpful.

**Comment by mark0263** [comment]
Confirmed that the minor code fixes have resolved the issue.

**Comment by spacequad** [comment]
Tested and confirmed...fixed.
